var dir_35e231cfaf39d44c1525e8247564e585 =
[
    [ "cpu", "dir_16bba3a4b121cf64f0e5026f87f5174d.html", "dir_16bba3a4b121cf64f0e5026f87f5174d" ],
    [ "cuda_hip", "dir_2176bdc4abbfee27816f3bddb372b87e.html", "dir_2176bdc4abbfee27816f3bddb372b87e" ],
    [ "sycl", "dir_ec54f3aadbd242b6a6d8fbc8a48a4315.html", "dir_ec54f3aadbd242b6a6d8fbc8a48a4315" ],
    [ "Properties.hpp", "Properties_8hpp.html", null ],
    [ "QueueCpuBlocking.hpp", "QueueCpuBlocking_8hpp.html", null ],
    [ "QueueCpuNonBlocking.hpp", "QueueCpuNonBlocking_8hpp.html", null ],
    [ "QueueCpuSyclBlocking.hpp", "QueueCpuSyclBlocking_8hpp.html", null ],
    [ "QueueCpuSyclNonBlocking.hpp", "QueueCpuSyclNonBlocking_8hpp.html", null ],
    [ "QueueCudaRtBlocking.hpp", "QueueCudaRtBlocking_8hpp.html", "QueueCudaRtBlocking_8hpp" ],
    [ "QueueCudaRtNonBlocking.hpp", "QueueCudaRtNonBlocking_8hpp.html", "QueueCudaRtNonBlocking_8hpp" ],
    [ "QueueFpgaSyclIntelBlocking.hpp", "QueueFpgaSyclIntelBlocking_8hpp.html", null ],
    [ "QueueFpgaSyclIntelNonBlocking.hpp", "QueueFpgaSyclIntelNonBlocking_8hpp.html", null ],
    [ "QueueGenericSyclBlocking.hpp", "QueueGenericSyclBlocking_8hpp.html", null ],
    [ "QueueGenericSyclNonBlocking.hpp", "QueueGenericSyclNonBlocking_8hpp.html", null ],
    [ "QueueGenericThreadsBlocking.hpp", "QueueGenericThreadsBlocking_8hpp.html", "QueueGenericThreadsBlocking_8hpp" ],
    [ "QueueGenericThreadsNonBlocking.hpp", "QueueGenericThreadsNonBlocking_8hpp.html", "QueueGenericThreadsNonBlocking_8hpp" ],
    [ "QueueGpuSyclIntelBlocking.hpp", "QueueGpuSyclIntelBlocking_8hpp.html", null ],
    [ "QueueGpuSyclIntelNonBlocking.hpp", "QueueGpuSyclIntelNonBlocking_8hpp.html", null ],
    [ "QueueHipRtBlocking.hpp", "QueueHipRtBlocking_8hpp.html", null ],
    [ "QueueHipRtNonBlocking.hpp", "QueueHipRtNonBlocking_8hpp.html", null ],
    [ "QueueUniformCudaHipRtBlocking.hpp", "QueueUniformCudaHipRtBlocking_8hpp.html", null ],
    [ "QueueUniformCudaHipRtNonBlocking.hpp", "QueueUniformCudaHipRtNonBlocking_8hpp.html", null ],
    [ "Traits.hpp", "queue_2Traits_8hpp.html", "queue_2Traits_8hpp" ]
];